User story "Add a basic entry"
felixcanditt/kultur-notiert pull request #14
Opened 2021-06-11 14:13 UTC by felixcanditt

Thanks for checking. You should see a console.log with all array items and title/category on screen. No storage yet.

2021-06-11 16:32 UTC, miriamhaenle requested changes
👏  Nice job! Just added a few comments.
Really appreciate the hotpink ❤️

2021-06-11 16:32 UTC, miriamhaenle commented on client/src/App.js
>  import Footer from './components/Footer';
This is great that you already consider a solid structure here and group the imports!

2021-06-11 16:32 UTC, miriamhaenle commented on client/src/App.js
> +  console.log('these are all stored items', watchlistItems);
Try to avoid mergin `console.logs` into `main`. This is not considered good practice :)

2021-06-11 16:32 UTC, miriamhaenle commented on client/src/App.js
> +    console.log('item to be added to db', newWatchListItem);
😼

2021-06-11 16:32 UTC, miriamhaenle commented on client/src/App.js
> +          <p>{serverMessage}</p>
Could this `<p>`-Tag also be within the Home-Page? It seems a bit odd to me to have a page components and add a paragraph below.

2021-06-11 16:32 UTC, miriamhaenle commented on client/src/App.js
> +            </div>
React always needs a key when mapping over items so that it can which items where updated / where changed [React Keys](https://reactjs.org/docs/lists-and-keys.html#keys)
```suggestion
          {watchlistItems.map((item, index) => (
            <div key={index}>
              <p>{item.title}</p>
              <p>{item.category}</p>
            </div>
```

2021-06-11 16:32 UTC, miriamhaenle commented on client/src/components/Header.js
>    background: hotpink;
❤️

2021-06-11 16:32 UTC, miriamhaenle commented on client/src/components/WatchlistForm.js
> +  const noItem = {
As this is used to set the initial State, best practice is to also call this `initialState` so it is clear what is the purpose of this object.

2021-06-11 16:32 UTC, miriamhaenle commented on client/src/components/WatchlistForm.js
> +    <FormStyled onSubmit={handleFormSubmit}>
As your React Component is called `WatchlistForm` you could also consider just naming this styled-component `Form`. 
However, this is rather a personal style question. I think the additional `styled` attribute is additional clutter but of course if you prefer it that way you can leave it.

2021-06-11 16:32 UTC, miriamhaenle commented on client/src/components/WatchlistForm.js
> +    margin: 0.7rem auto 0 auto;
As you use `auto` both left and right you can use the shorthand here.
```suggestion
    margin: 0.7rem auto 0;
```

2021-06-14 08:54 UTC, felixcanditt commented on client/src/App.js
> +  console.log('these are all stored items', watchlistItems);
deleted them

2021-06-14 08:54 UTC, felixcanditt commented on client/src/App.js
> +    console.log('item to be added to db', newWatchListItem);
deleted

2021-06-14 08:58 UTC, felixcanditt commented on client/src/App.js
> +          <p>{serverMessage}</p>
adjusted this accordingly

2021-06-14 09:01 UTC, felixcanditt commented on client/src/App.js
> +            </div>
adjusted this

2021-06-14 09:02 UTC, felixcanditt commented on client/src/components/WatchlistForm.js
> +  const noItem = {
adjusted

2021-06-14 09:04 UTC, felixcanditt commented on client/src/components/WatchlistForm.js
> +    margin: 0.7rem auto 0 auto;
adjusted

2021-06-14 09:11 UTC, felixcanditt commented on client/src/components/WatchlistForm.js
> +    <FormStyled onSubmit={handleFormSubmit}>
thanks, adjusted this :)

2021-06-14 09:13 UTC, merged