Replaced index by uuid // Added cancel button
felixcanditt/kultur-notiert pull request #30
Opened 2021-06-21 15:14 UTC by felixcanditt

Thanks for your review :)

Things that changed:
I replaced index by uuid for a smoother handling of filter/remove functions.
I added a cancel button to the forms in Watchlist and Library that works while adding or editing an item.

2021-06-21 16:03 UTC, ThomasKirst requested changes
Great work overall and good naming of components and functions!

Only a few remarks :)

2021-06-22 09:53 UTC, felixcanditt commented on client/src/App.js
> +  console.log(itemToBeEdited);
removed

2021-06-22 09:53 UTC, felixcanditt commented on client/src/App.js
> +    const editedWatchlist = watchlist.filter(
renamed

2021-06-22 10:02 UTC, felixcanditt commented on client/src/components/WatchlistForm.js
> +        <button type="reset" onClick={() => handleFormCancelation()}>
adjusted

2021-06-22 10:03 UTC, felixcanditt commented on client/src/components/LibraryCards.js
>          <Card key={index}>
adjusted

2021-06-22 11:57 UTC, anitaschiller requested changes

2021-06-22 12:55 UTC, felixcanditt commented on package.json
>      "test": "echo \"Error: no test specified\" && exit 1",
adjusted

2021-06-22 12:57 UTC, felixcanditt commented on package.json
> +    "dev": "npm run client",
adjusted

2021-06-22 13:00 UTC, merged