Library rating
felixcanditt/kultur-notiert pull request #32
Opened 2021-06-23 08:45 UTC by felixcanditt

Thanks for your review.

My pull request is connected to this [user story](https://github.com/felixcanditt/kultur-notiert/issues/25).
Rating isn't shown in Library Cards as stars yet, just as text.
I haven't refactored/outsourced yet, please check if this looks good for now so that I can go on with it :)

2021-06-23 08:47 UTC, felixcanditt commented on client/src/components/LibraryCard.js
> +
Will still refactor lines 12-19, please ignore

2021-06-23 09:50 UTC, anitaschiller requested changes
Hi Felix, looks good but needs some work. 😸

2021-06-23 09:50 UTC, anitaschiller commented on client/src/components/LibraryForm.js
> +          alt="this is a star for rating purposes"
Since your application language is German, you can also use German `alt` texts.

2021-06-23 09:50 UTC, anitaschiller commented on client/src/components/LibraryForm.js
> +        />
DRY :-) - you are using the same code for each <img>, so a function that generates the image tags and receives the rating value as a parameter could save several lines of code.

2021-06-23 09:50 UTC, anitaschiller commented on client/src/components/LibraryForm.js
> +    rating: '',
Shouldn't your rating be a number? If yes, you can initialize the rating with 0.

2021-06-23 09:50 UTC, anitaschiller commented on client/src/components/LibraryForm.js
> +      ? setFormItem({ ...formItem, rating: '' })
See comment above. Rating could be set with 0.

2021-06-23 16:06 UTC, felixcanditt commented on client/src/components/LibraryForm.js
> +    rating: '',
changed that

2021-06-23 16:06 UTC, felixcanditt commented on client/src/components/LibraryForm.js
> +          alt="this is a star for rating purposes"
adjusted

2021-06-23 16:08 UTC, felixcanditt commented on client/src/components/LibraryForm.js
> +      ? setFormItem({ ...formItem, rating: '' })
changed that

2021-06-23 17:09 UTC, felixcanditt commented on client/src/components/LibraryForm.js
> +        />
updated

2021-06-24 12:09 UTC, anitaschiller approved these changes
Well done Felix, approved! :)

2021-06-24 12:09 UTC, anitaschiller commented on client/src/components/LibraryFormStars.js
> +    </Stars>
Very nice refactoring! :) We like!

2021-06-24 12:53 UTC, merged